# Change these first
owner: Swerv-Ltd # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Web App
    url: https://web.swyftpay.io
    icon: https://web.swyftpay.io/favicon.ico
  - name: Website
    url: https://swyftpay.io
    icon: https://web.swyftpay.io/favicon.ico
  - name: Play store
    url: https://play.google.com/store/apps/details?id=app.swyft.swyft_prod
    icon: https://web.swyftpay.io/favicon.ico
  - name: App store
    url: https://apps.apple.com/ng/app/swyft-multicurrency-wallet/id6443740202
    icon: https://web.swyftpay.io/favicon.ico
assignees: # Users to assign downtime issues (optional)
  - mujhtech

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.swyftpay.io
  baseUrl: /status
  logoUrl: https://web.swyftpay.io/favicon.ico
  name: Swerv
  introTitle: "**Swerv** building the future of payment"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/Swerv-Ltd/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
